### ISSUE TITLE
Test  Android-JS

### ISSUE THREAD

**Issue by wanghuan1115** [sdkbox/sdkbox-bee7-sample#10]
以下为 bee7 android js 版本的测试结果

### show game wall

点击进入奖励商店
无法加载可获取奖励的广告视频

### bee7Points=0 virtualCurrencyAmount=0

点击无任何作用，也无输出

注: sample 执行 cocos run -p android 打包失败，需要 eclipse 手动引入 google-play-services_lib 打包。

**Comment by yinjimmy** [comment]
test with https://github.com/sdkbox/sdkbox-bee7-sample/commit/7a41d4ced4ec27fa75c57ec33cd4b50fea8b65f2

0. cocos run -p android (正常编译启动)
1. 需要等待 show game wall 的状态从灰色变为白色， 然后点击
2. 在 gamewall 里面找视频广告播放
3. 播放完成，得到奖励

ok with
- 红米1
- android 4.2.1
